name: CI/CD Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Set Up SSH (inject in agent)
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Debug SSH Key (OPTIONNEL, pour debug - effacer après)
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ls -l ~/.ssh/
          head -5 ~/.ssh/id_rsa

      - name: Test SSH connection (mode agent )
        run: ssh -vvv ${{ secrets.USER }}@${{ secrets.SERVER_IP }} "echo OK agent"

      - name: Test SSH connection (clé fichier)
        run: ssh -i ~/.ssh/id_rsa -vvv ${{ secrets.USER }}@${{ secrets.SERVER_IP }} "echo OK file"

      - name: Deploy to OVH
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.SERVER_IP }} '
            cd /home/ubuntu/inolib-website/packages/app-www
            git fetch origin main
            git reset --hard origin/main
            pnpm install --frozen-lockfile
            pnpm run build
            pm2 reload nextjs-front --update-env
          '
